import { existsSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import type { Command } from 'commander'
import chalk from 'chalk'

/**
 * Register the `nexsync init` command.
 * Scaffolds the minimal files needed to start using NexSync.
 */
export function registerInitCommand(program: Command): void {
  program
    .command('init')
    .description('Set up NexSync in the current project')
    .option('--framework <name>', 'Framework: react | vue | react-native | vanilla', 'react')
    .action((opts: { framework: string }) => {
      const cwd = process.cwd()
      const framework = opts.framework as 'react' | 'vue' | 'react-native' | 'vanilla'

      console.log()
      console.log(chalk.bold('NexSync init'))
      console.log(chalk.dim(`Framework: ${framework}\n`))

      // Write a .env.local with a placeholder relay URL
      const envPath = join(cwd, '.env.local')
      if (!existsSync(envPath)) {
        writeFileSync(envPath, 'NEXT_PUBLIC_RELAY_URL=ws://localhost:8080\n')
        console.log(chalk.green('✔') + '  Created .env.local')
      } else {
        console.log(chalk.dim('·  .env.local already exists — skipped'))
      }

      // Write a starter file
      const srcDir = join(cwd, 'src')
      if (!existsSync(srcDir)) mkdirSync(srcDir, { recursive: true })

      const starterPath = join(srcDir, 'nexsync.ts')
      if (!existsSync(starterPath)) {
        writeFileSync(starterPath, starterFile(framework))
        console.log(chalk.green('✔') + '  Created src/nexsync.ts')
      } else {
        console.log(chalk.dim('·  src/nexsync.ts already exists — skipped'))
      }

      console.log()
      console.log(chalk.bold('Next steps:'))
      console.log(
        `  1. ${chalk.cyan('nexsync relay dev')}  — start a local relay`,
      )
      console.log(
        `  2. Import ${chalk.cyan(`@nexsync/${framework === 'vanilla' ? 'core' : framework}`)} and wrap your app`,
      )
      console.log(
        `  3. ${chalk.cyan('nexsync relay deploy --platform fly')}  — ship to production`,
      )
      console.log()
    })
}

function starterFile(framework: 'react' | 'vue' | 'react-native' | 'vanilla'): string {
  switch (framework) {
    case 'react':
      return `// src/nexsync.ts — generated by nexsync init
// Wrap your root component with <NexSyncProvider> to enable sync.

export { NexSyncProvider, useNexSync, useValue, useQuery, useStatus } from '@nexsync/react'
`
    case 'vue':
      return `// src/nexsync.ts — generated by nexsync init
// Install the plugin in main.ts: app.use(createNexSync({ relay: process.env.VITE_RELAY_URL }))

export { createNexSync, useNexSync, useValue, useQuery, useStatus } from '@nexsync/vue'
`
    case 'react-native':
      return `// src/nexsync.ts — generated by nexsync init
// Wrap your root component with <NexSyncProvider> to enable offline-first sync.

export { NexSyncProvider, useNexSync, useValue, useQuery, useStatus } from '@nexsync/react-native'
`
    default:
      return `// src/nexsync.ts — generated by nexsync init
import { NexSync } from '@nexsync/core'

const relay = process.env['RELAY_URL'] ?? 'ws://localhost:8080'

export const db = new NexSync({ relay, appId: 'my-app' })
`
  }
}
